### ISSUE TITLE
neat 1.15.2 forge server bug

### ISSUE THREAD

**Issue by Teoballo1** [VazkiiMods/Neat#63]
I really love this mod and I think its the best health indicator for 1.15.2 at the least but I noticed it blocks joining in to forge servers not using the mod, but at the same time it can not be used on servers as it is a client side only mod
forge servers will have a large red X displaying "FML modded server network message list is not compatible" when neat is loaded on the client.  Thank you for looking over this and if i forgot to add anything important that can't be tested for whatever reasons ill do my best to add what is needed.

**Comment by Vaelzan** [comment]
I submitted a fix for that issue back in June (https://github.com/Vazkii/Neat/pull/54). For some reason Vazkii never released an updated version on 1.15.2, which is disappointing since the fix is there and has been for months.

You can add Neat to a server though as a workaround despite being a client side mod. It won't do anything except fix that issue.
